#!/bin/bash

echo "installig stuff"

#start with basic stuff
sh $HOME/runs/basic

#now some fonts
sh $HOME/runs/nerdfonts

#rust utils
sh $HOME/runs/rust_tools

#fish shell
sh $HOME/runs/fish_shell

#docker desktop
sh $HOME/runs/docker_desktop

#editors
sh $HOME/runs/code_editors

#apps i use
sh $HOME/runs/capacities

#finally, set the repo url to use SSH
echo "Updating the yadm repo origin URL"
yadm remote set-url origin git@github.com:aeyquem/arch-dotfiles.git

