#!/bin/bash

#base config
cd $HOME
mkdir Apps

sudo pacman -S wget
sudo pacman -S base-devel

#install yay
cd $HOME/Apps
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si

#now install neovim to have an editor
sudo pacman -S neovim
