#!/bin/bash

#download docker
# wget https://download.docker.com/linux/static/stable/x86_64/docker-28.0.4.tgz -qO- | tar xvfz - docker/docker --strip-components=1
# sudo mv ./docker /usr/local/bin

# #dowload docker desktop
# wget https://desktop.docker.com/linux/main/amd64/184744/docker-desktop-x86_64.pkg.tar.zst

# #install package
# sudo pacman -U ./docker-desktop-x86_64.pkg.tar.zst

yay -S docker-desktop
